### ISSUE TITLE
Pressing back in interview with audio recording causes audio problems / crashes

### ISSUE THREAD

**Issue by uozuAho** [RHoKAustralia/melb-timor-leste#40]
In develop: f29562a

Steps to reproduce:
- Start 'API duplicate' interview
- Answer two questions, then press back twice when the third question is recording

After this, recording & playback no longer work in any app until the next reboot. The phone will reboot by itself after a minute or so :worried: 

I'm guessing that AudioThread isn't being cleaned up correctly when navigating backwards, and it's holding onto MediaRecorder and MediaPlayer so nothing else can use it.

**Comment by rockgecko-development** [comment]
I've found the problem:
When you hit back, fragments are popped *_synchronously *_ using `popBackStack`, but the `AudioThread` is stopped by posting a message to its `handler`.
So the previous fragment has `onResume` called before the top fragment has fully stopped its `AudioThread`, therefore it actually ends up with the same `AudioThread` object. This has other problems too, such as the previous fragment will now have the top fragment's filename!

The quick fix is to put the `AudioThread` `startAudioThreadIfNull` into a `View.postDelayed(Runnable, delay)` method in `onResume`.
